Update documentation

diff --git a/check-and-monitor b/check-and-monitor
--- a/check-and-monitor
+++ b/check-and-monitor
@@ -1,7 +1,7 @@
 #!/bin/bash
 #    check-and-monitor - check and monitor connections or anything
 #
-#    Copyright (C) 2021 luc.deschenaux@freesurf.ch
+#    Copyright (C) 2021-2024 luc.deschenaux@freesurf.ch
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU Affero General Public License as published
@@ -50,40 +50,47 @@ DESCRIPTION
        -h, --help
 
        -l, --load-config <filename>
-               load configuration from file
+               Load configuration from file
+               Options specified after -l will override loaded settings
 
        -i, --interval <$interval>
-               sleep interval between attempts
+               Sleep interval between attempts
 
        -t, --timeout  <$timeout>
-               attempt timeout in seconds
+               Attempt timeout in seconds
 
        -f, --failures <$failures_threshold>
-               notify failure after specified failed attempts
+               Notify failure after specified failed attempts
 
        -s, --successes <$successes_threshold>
-               notify success after specified succeeded attempts
+               Notify success after specified succeeded attempts
 
        -n, --notify-command <notify-send>
-               default command for --notify-success and --notify-failure
+               Default command for --notify-success and --notify-failure
+               Variables of interest:
+                 \$1                   - The "--notify_success" or
+                                         "--notify_failure" message, evaluated
+                 \$command_exit_code   - The exit code of --command
+                 \$argv[]              - Command line parameters
+                                        (see example configuration file below)
 
        -Y, --notify-success <'\$notify "Connection to \$1:\$2 succeeded!"'>
-               command for notifying successful attempts
+               Command for notifying successful attempts
 
        -N, --notify-failure <'\$notify "Connection to \$1:\$2 failed!"'>
-               command for notifying failed attempts
+               Command for notifying failed attempts
 
        -v, --verbose
-               report command output not only on status change
+               Report command output not only on status change
 
        -m, --monitor <86400>
-                seconds before success or failure re-notification
+                Seconds before success or failure re-notification
 
        -S, --monitor-success <$monitor_success>
-                seconds before success re-notification
+                Seconds before success re-notification
 
        -F, --monitor-failure <$monitor_failure>
-                seconds before failure re-notification
+                Seconds before failure re-notification
 
        -c, --command <'nc -w \$timeout -v -z \$1 \$2 2>&1'>
                 Command to run for checking whatever the check.
@@ -93,7 +100,7 @@ DESCRIPTION
 CONFIGURATION FILE
        When file ~/.check-and-monitor.conf exists it is evaluated before
        command line options.
-       Command line options override settings from ~/..check-and-monitor.conf.
+       Command line options override settings from ~/.check-and-monitor.conf.
 
        You can also specify a configuration file with -l|--load-config.
        Options specified after -l will override settings from the config file.
@@ -111,6 +118,9 @@ CONFIGURATION FILE
            command='nc -w \$timeout -v -z \$1 \$2 2>&1'
 
        EXAMPLE CONFIGURATION FILE:
+           # Send a mail to user@host on host un/reachable
+           # with full traceroute output on failure,
+           # and only the first gateway on success
            dest=user@host
            mail-send() {
                if [ \$command_exit_code -eq 0 ] ; then
@@ -137,6 +147,8 @@ fi
 
 eval set -- "$options"
 
+# Not using shift $((OPTIND-1)) allows command line parameters before options
+# eg: check-and-monitor myhost 80 -t 30
 while [ $# -gt 0 ] ; do
   case $1 in
     -h|--help) usage ;;
@@ -154,7 +166,7 @@ while [ $# -gt 0 ] ; do
     -G|--notify-failure) notify_failure=$2 ; shift ;;
     -c|--command) command=$2 ; shift ;;
       (--) shift; break ;;
-      (-*) echo "$(basename $0): error - unrecognized option $1" 1>&2; exit 1 ;;
+      (-*) echo "$(basename $0): error - unrecognized option $1" >&2; exit 1 ;;
       (*) break ;;
   esac
   shift
