v1.0
- Implement default and loadable configuration files
- Rename options -G and -T to -Y and -N

diff --git a/check-and-monitor b/check-and-monitor
--- a/check-and-monitor
+++ b/check-and-monitor
@@ -7,12 +7,12 @@
 #    it under the terms of the GNU Affero General Public License as published
 #    by the Free Software Foundation, either version 3 of the License, or
 #    (at your option) any later version.
-# 
+#
 #    This program is distributed in the hope that it will be useful,
 #    but WITHOUT ANY WARRANTY; without even the implied warranty of
 #    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #    GNU Affero General Public License for more details.
-# 
+#
 #    You should have received a copy of the GNU Affero General Public License
 #    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
@@ -33,7 +33,7 @@ nc='nc -w $timeout -v -z $1 $2 2>&1'
 command="$nc"
 
 usage() {
-cat << EOF
+  cat << EOF
 NAME
        $(basename $0) - monitor connection to tcp server or anything
 
@@ -49,7 +49,10 @@ DESCRIPTION
 
        -h, --help
 
-       -i, --interval <$interval> 
+       -l, --load-config <filename>
+               load configuration from file
+
+       -i, --interval <$interval>
                sleep interval between attempts
 
        -t, --timeout  <$timeout>
@@ -60,14 +63,14 @@ DESCRIPTION
 
        -s, --successes <$successes_threshold>
                notify success after specified succeeded attempts
-       
+
        -n, --notify-command <notify-send>
                default command for --notify-success and --notify-failure
 
-       -T, --notify-success <'\$notify "Connection to \$1:\$2 succeeded!"'>
+       -Y, --notify-success <'\$notify "Connection to \$1:\$2 succeeded!"'>
                command for notifying successful attempts
 
-       -G, --notify-failure <'\$notify "Connection to \$1:\$2 failed!"'>
+       -N, --notify-failure <'\$notify "Connection to \$1:\$2 failed!"'>
                command for notifying failed attempts
 
        -v, --verbose
@@ -75,34 +78,69 @@ DESCRIPTION
 
        -m, --monitor <86400>
                 seconds before success or failure re-notification
-       
+
        -S, --monitor-success <$monitor_success>
                 seconds before success re-notification
 
-       -F, --monitor-failure <$monitor_failure> 
+       -F, --monitor-failure <$monitor_failure>
                 seconds before failure re-notification
 
        -c, --command <'nc -w \$timeout -v -z \$1 \$2 2>&1'>
                 Command to run for checking whatever the check.
                 When you change this for something where \$1 and \$2 means
-                anything else than host:port you need to set -T and -G.
+                anything else than host:port you need to set -Y and -N.
+
+CONFIGURATION FILE
+       When file ~/.check-and-monitor.conf exists it is evaluated before
+       command line options.
+       Command line options override settings from ~/..check-and-monitor.conf.
+
+       You can also specify a configuration file with -l|--load-config.
+       Options specified after -l will override settings from the config file.
+
+       DEFAULT CONFIGURATION:
+           timeout=10
+           interval=60
+           failures_threshold=3
+           successes_threshold=0
+           monitor_success=86400
+           monitor_failure=86400
+           notify=notify-send
+           notify_success='\$notify "Connection to \$1:\$2 succeeded!"'
+           notify_failure='\$notify "Connection to \$1:\$2 failed!"'
+           command='nc -w \$timeout -v -z \$1 \$2 2>&1'
+
+       EXAMPLE CONFIGURATION FILE:
+           dest=user@host
+           mail-send() {
+               if [ \$command_exit_code -eq 0 ] ; then
+                  msg=\$(traceroute -m 1 \${argv[0]})
+                else
+                  msg=\$(traceroute \${argv[0]})
+               fi
+               mail \$dest -s "\$1" <<< "msg"
+             }
+           notify=mail-send
 
 EOF
-exit 1
+  exit 1
 }
 
+[ -f ~/.check-and-monitor.conf ] && . ~/.check-and-monitor.conf
+
 # parse command line options
-if ! options=$(getopt -o hi:t:f:s:vm:S:F:n:T:G:c: -l help,interval:,timeout:,failures:,successes:,verbose,monitor:,monitor-success:,monitor-failure:,notify-command:,notify-success:,notify-failure:,command: -- "$@")
+if ! options=$(getopt -o l:hi:t:f:s:vm:S:F:n:Y:N:c: -l load-config:,help,interval:,timeout:,failures:,successes:,verbose,monitor:,monitor-success:,monitor-failure:,notify-command:,notify-success:,notify-failure:,command: -- "$@")
 then
-    # something went wrong, getopt will put out an error message for us
-    exit 1
+  # something went wrong, getopt will put out an error message for us
+  exit 1
 fi
 
 eval set -- "$options"
 
 while [ $# -gt 0 ] ; do
-    case $1 in
+  case $1 in
     -h|--help) usage ;;
+    -l|--load-config) . "$2" ; shift ;;
     -i|--interval) interval=$2 ; shift ;;
     -t|--timeout) timeout=$2 ; shift ;;
     -f|--failures) failures_threshold=$2 ; shift ;;
@@ -115,24 +153,27 @@ while [ $# -gt 0 ] ; do
     -T|--notify-success) notify_success=$2 ; shift ;;
     -G|--notify-failure) notify_failure=$2 ; shift ;;
     -c|--command) command=$2 ; shift ;;
-    (--) shift; break;;
-    (-*) echo "$(basename $0): error - unrecognized option $1" 1>&2; exit 1;;
-    (*) break;;
-    esac
-    shift
+      (--) shift; break ;;
+      (-*) echo "$(basename $0): error - unrecognized option $1" 1>&2; exit 1 ;;
+      (*) break ;;
+  esac
+  shift
 done
 
 if [ "$command" = "$nc" ] ; then
-  if [ $# -lt 2 ];then
+  if [ $# -lt 2 ] ; then
     usage
-    exit 1;
+    exit 1
   fi
-else 
+else
   echo "INFO: command line parameters: $@"
 fi
 
+# for user scripts
+argv=($@)
+
 check(){
-	t0=$(date +%s.%N)
+  t0=$(date +%s.%N)
   result=$(eval $command)
   command_exit_code="$?"
   t1=$(date +%s.%N)
@@ -147,8 +188,9 @@ while true ; do
   now=$(date +%s)
   notified_since=$(expr $now - $notified_at)
   check "$@"
-  if [ $command_exit_code -eq 0 ]; then
+  if [ $command_exit_code -eq 0 ] ; then
     ((successes++))
+    failures=0
     if [ $successes -gt $successes_threshold ] ; then
       [ $notified_since -gt $monitor_success ] && notified=no
       if [ $hasfailed = yes -o $notified = no ] ; then
@@ -164,10 +206,10 @@ while true ; do
         fi
       fi
       hasfailed=no
-      failures=0
     fi
   else
     ((failures++))
+    successes=0
     if [ $failures -gt $failures_threshold ] ; then
       [ $hasfailed != yes ] && notified=no
       [ $notified_since -gt $monitor_failure ] && notified=no
@@ -184,7 +226,6 @@ while true ; do
         fi
       fi
       hasfailed=yes
-      successes=0
     fi
   fi
   sleep $interval
