--notify-* options becomes --on*, added examples/
Renamed --notify-success and --notify-failure to --onsuccess and --onfailure
Added --pidfile option
Added --output option to redirect stdout and stderr
Added example for restarting wireguard in examples/wgcheck.conf

diff --git a/check-and-monitor b/check-and-monitor
--- a/check-and-monitor
+++ b/check-and-monitor
@@ -1,7 +1,7 @@
 #!/bin/bash
 #    check-and-monitor - check and monitor connections or anything
 #
-#    Copyright (C) 2021-2024 luc.deschenaux@freesurf.ch
+#    Copyright (C) 2021-2025 luc.deschenaux@freesurf.ch
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU Affero General Public License as published
@@ -25,27 +25,28 @@ successes_threshold=0
 hasfailed=dunno
 notified=no
 monitor_success=86400
-monitor_failure=86400
-notify=notify-send
-notify_success='$notify "Connection to $1:$2 succeeded!"'
-notify_failure='$notify "Connection to $1:$2 failed!"'
+monitor_failure=3600
+notify=echo
+onsuccess='$notify "Connection to $1:$2 succeeded!"'
+onfailure='$notify "Connection to $1:$2 failed!"'
 nc='nc -w $timeout -v -z $1 $2 2>&1'
+output=cat
 command="$nc"
 
 usage() {
   cat << EOF
 NAME
-       $(basename $0) - monitor connection to tcp server or anything
+       $(basename $0) - monitor connection to tcp server, or anything else
 
 SYNOPSIS
-       $(basename $0) [OPTION]... [<server> <port>]
+       $(basename $0) [OPTION]... [<arg> ...]
 
 DESCRIPTION
        Unless you specify something else to check (using the --command option
-       below), this command will check tcp connection to <server> <port>
-       every <--interval> seconds, run notification command after <--failures>
+       below), this command will check tcp connection to <arg1> on port <arg2>
+       every <--interval> seconds, run <--onfailure> command after <--failures>
        attempts, and forces re-notification after <--monitor> seconds.
-       All the options below are optional.
+       All the options below are then optional.
 
        -h, --help
 
@@ -66,36 +67,53 @@ DESCRIPTION
                Notify success after specified succeeded attempts
 
        -n, --notify-command <notify-send>
-               Default command for --notify-success and --notify-failure
+               Default command for default --onsuccess and --onfailure
                Variables of interest:
-                 \$1                   - The "--notify_success" or
-                                         "--notify_failure" message, evaluated
+                 \$1                   - The "--onsuccess" or
+                                         "--onfailure" message, evaluated
                  \$command_exit_code   - The exit code of --command
                  \$argv[]              - Command line parameters
                                         (see example configuration file below)
 
-       -Y, --notify-success <'\$notify "Connection to \$1:\$2 succeeded!"'>
-               Command for notifying successful attempts
+       -Y, --onsuccess <'\$notify "Connection to \$1:\$2 succeeded!"'>
+               Command for notifying successful attempts.
+               Can be set to empty string.
 
-       -N, --notify-failure <'\$notify "Connection to \$1:\$2 failed!"'>
-               Command for notifying failed attempts
+       -N, --onfailure <'\$notify "Connection to \$1:\$2 failed!"'>
+               Command for notifying failed attempts.
+               Can be set to empty string.
 
        -v, --verbose
                Report command output not only on status change
 
        -m, --monitor <86400>
                 Seconds before success or failure re-notification
+                -1: disable re-notifications
 
        -S, --monitor-success <$monitor_success>
-                Seconds before success re-notification
+                Seconds before success re-notification (overrides --monitor)
+                -1: disable re-notifications
 
        -F, --monitor-failure <$monitor_failure>
-                Seconds before failure re-notification
+                Seconds before failure re-notification (overrides --monitor)
+                -1: disable re-notifications
 
        -c, --command <'nc -w \$timeout -v -z \$1 \$2 2>&1'>
                 Command to run for checking whatever the check.
                 When you change this for something where \$1 and \$2 means
                 anything else than host:port you need to set -Y and -N.
+
+       -o, --output <cat>
+                Allow redirecting stdout and stderr
+                eg:
+                    -o logger
+                or
+                    -o 'ts "[%Y-%m-%d %H:%M:%S]"'
+
+       -p, --pid-file <filename>
+                Do not run the script if another process with matching command
+                line is running with the same pid, else store the pid there.
+
 
 CONFIGURATION FILE
        When file ~/.check-and-monitor.conf exists it is evaluated before
@@ -112,10 +130,11 @@ CONFIGURATION FILE
            successes_threshold=0
            monitor_success=86400
            monitor_failure=86400
-           notify=notify-send
-           notify_success='\$notify "Connection to \$1:\$2 succeeded!"'
-           notify_failure='\$notify "Connection to \$1:\$2 failed!"'
+           notify=echo
+           onsuccess='\$notify "Connection to \$1:\$2 succeeded!"'
+           onfailure='\$notify "Connection to \$1:\$2 failed!"'
            command='nc -w \$timeout -v -z \$1 \$2 2>&1'
+           output=cat
 
        EXAMPLE CONFIGURATION FILE:
            # Send a mail to user@host on host un/reachable
@@ -131,114 +150,149 @@ CONFIGURATION FILE
                mail \$dest -s "\$1" <<< "msg"
              }
            notify=mail-send
+           monitor_failure=900
+           output=logger
+
+       EXAMPLE CONFIGURATION FILE:
+           # Restart wireguard tunnel after 3 failed pings through the tunnel.
+           # Run with check-and-monitor -l <this-config> <wg0> <peer-ip>
+           wg_restart() {
+             IFACE=${argv[0]}
+             ip link show $IFACE > /dev/null 2>&1 && wg-quick down $IFACE
+             wg-quick up $IFACE
+           }
+           timeout=5
+           failures_threshold=3
+           successes_threshold=0
+           monitor_success=-1
+           monitor_failure=0
+           onsuccess='echo "$1: host $2 is up!"'
+           onfailure=wg_restart
+           command='ping -c 1 -w $timeout ${argv[1]} 2>&1'
 
 EOF
   exit 1
 }
 
-[ -f ~/.check-and-monitor.conf ] && . ~/.check-and-monitor.conf
+{
+  [ -f ~/.check-and-monitor.conf ] && . ~/.check-and-monitor.conf
 
-# parse command line options
-if ! options=$(getopt -o l:hi:t:f:s:vm:S:F:n:Y:N:c: -l load-config:,help,interval:,timeout:,failures:,successes:,verbose,monitor:,monitor-success:,monitor-failure:,notify-command:,notify-success:,notify-failure:,command: -- "$@")
-then
-  # something went wrong, getopt will put out an error message for us
-  exit 1
-fi
-
-eval set -- "$options"
-
-# Not using shift $((OPTIND-1)) allows command line parameters before options
-# eg: check-and-monitor myhost 80 -t 30
-while [ $# -gt 0 ] ; do
-  case $1 in
-    -h|--help) usage ;;
-    -l|--load-config) . "$2" ; shift ;;
-    -i|--interval) interval=$2 ; shift ;;
-    -t|--timeout) timeout=$2 ; shift ;;
-    -f|--failures) failures_threshold=$2 ; shift ;;
-    -s|--successes) successes_threshold=$2 ; shift ;;
-    -v|--verbose) verbose=yes ;;
-    -m|--monitor) monitor_success=$2 ; monitor_failure=$2 ; shift ;;
-    -S|--monitor-success) monitor_success=$2 ; shift ;;
-    -F|--monitor-failure) monitor_failure=$2 ; shift ;;
-    -n|--notify-command) notify=$2 ; shift ;;
-    -T|--notify-success) notify_success=$2 ; shift ;;
-    -G|--notify-failure) notify_failure=$2 ; shift ;;
-    -c|--command) command=$2 ; shift ;;
-      (--) shift; break ;;
-      (-*) echo "$(basename $0): error - unrecognized option $1" >&2; exit 1 ;;
-      (*) break ;;
-  esac
-  shift
-done
-
-if [ "$command" = "$nc" ] ; then
-  if [ $# -lt 2 ] ; then
-    usage
+  # parse command line options
+  if ! options=$(getopt -o l:hi:t:f:s:vm:S:F:n:Y:N:c:o:p: -l load-config:,help,interval:,timeout:,failures:,successes:,verbose,monitor:,monitor-success:,monitor-failure:,notify-command:,onsuccess:,onfailure:,command:,output:,pidfile: -- "$@")
+  then
+    # something went wrong, getopt will put out an error message for us
     exit 1
   fi
-else
-  echo "INFO: command line parameters: $@"
-fi
 
-# for user scripts
-argv=($@)
+  eval set -- "$options"
 
-check(){
-  t0=$(date +%s.%N)
-  result=$(eval $command)
-  command_exit_code="$?"
-  t1=$(date +%s.%N)
-  t=$(bc <<< "$t1-$t0")
-  status="$result ($(printf %f $t)s)"
-  [ -n "$verbose" ] && echo $status
-}
+  # for user scripts
+  argv=()
 
-#set -x
-notified_at=0
-while true ; do
-  now=$(date +%s)
-  notified_since=$(expr $now - $notified_at)
-  check "$@"
-  if [ $command_exit_code -eq 0 ] ; then
-    ((successes++))
-    failures=0
-    if [ $successes -gt $successes_threshold ] ; then
-      [ $notified_since -gt $monitor_success ] && notified=no
-      if [ $hasfailed = yes -o $notified = no ] ; then
-        [ -z "$verbose" ] && echo $status
-        eval $notify_success
-        notify_exit_code=$?
-        if [ $notify_exit_code -eq 0 ] ; then
-          notified=yes
-          notified_at=$(date +%s)
-        else
-          notified=no
-          echo "ERROR: success notification failed ! ($notify_exit_code)" >& 2
-        fi
-      fi
-      hasfailed=no
+  while [ $# -gt 0 ] ; do
+    case $1 in
+      -h|--help) usage ;;
+      -l|--load-config) . "$2" ; shift ;;
+      -i|--interval) interval=$2 ; shift ;;
+      -t|--timeout) timeout=$2 ; shift ;;
+      -f|--failures) failures_threshold=$2 ; shift ;;
+      -s|--successes) successes_threshold=$2 ; shift ;;
+      -v|--verbose) verbose=yes ;;
+      -m|--monitor) monitor_success=$2 ; monitor_failure=$2 ; shift ;;
+      -S|--monitor-success) monitor_success=$2 ; shift ;;
+      -F|--monitor-failure) monitor_failure=$2 ; shift ;;
+      -n|--notify-command) notify=$2 ; shift ;;
+      -Y|--onsuccess) onsuccess=$2 ; shift ;;
+      -N|--onfailure) onfailure=$2 ; shift ;;
+      -c|--command) command=$2 ; shift ;;
+      -o|--output) output=$2 ; shift ;;
+      -p|--pid-file) pidfile=$2 ; shift ;;
+        (--) shift; argv+=($@) ; break ;;
+        (-*) echo "$(basename $0): error - unrecognized option $1" >&2; exit 1 ;;
+        (*) argv+=($1) ; shift ;;
+    esac
+    shift
+  done
+
+  if [ "$command" = "$nc" ] ; then
+    if [ $# -lt 2 ] ; then
+      usage
+      exit 1
     fi
   else
-    ((failures++))
-    successes=0
-    if [ $failures -gt $failures_threshold ] ; then
-      [ $hasfailed != yes ] && notified=no
-      [ $notified_since -gt $monitor_failure ] && notified=no
-      if [ $notified = no ] ; then
-        [ -z "$verbose" ] && echo $status
-        eval $notify_failure
-        notify_exit_code=$?
-        if [ $notify_exit_code -eq 0 ] ; then
-          notified=yes
-          notified_at=$(date +%s)
-        else
-          notified=no
-          echo "ERROR: failure notification failed ! ($notify_exit_code)" >& 2
-        fi
-      fi
-      hasfailed=yes
+    echo "INFO: command line parameters: $@"
+  fi
+
+  if [ -f $pidfile ] ; then
+    PID=$(cat $pidfile)
+    # exit if PID is still running and script name matches ours somehow
+    if kill -0 "$PID" 2> /dev/null &&
+      [ -r /proc/$PID/cmdline ] &&
+      xargs -0 echo < /proc/$PID/cmdline | grep -q $(basename $0)
+    then
+#       echo already running with pid $PID
+       exit
     fi
   fi
-  sleep $interval
-done
+  echo $$ > $pidfile
+
+  check(){
+    t0=$(date +%s.%N)
+    result=$(eval $command)
+    command_exit_code="$?"
+    t1=$(date +%s.%N)
+    t=$(bc <<< "$t1-$t0")
+    status="$result ($(printf %f $t)s)"
+    [ -n "$verbose" ] && echo $status
+  }
+
+  #set -x
+  notified_at=0
+  while true ; do
+    now=$(date +%s)
+    notified_since=$(expr $now - $notified_at)
+    check "$@"
+    if [ $command_exit_code -eq 0 ] ; then
+      ((successes++))
+      failures=0
+      if [ $successes -ge $successes_threshold ] ; then
+        [ $notified_since -gt $monitor_success ] && [ $monitor_success -ge 0 ] && notified=no
+        if [ $hasfailed = yes -o $notified = no ] ; then
+          [ -z "$verbose" ] && echo $status
+          eval $onsuccess
+          notify_exit_code=$?
+          if [ $notify_exit_code -eq 0 ] ; then
+            notified=yes
+            notified_at=$(date +%s)
+          else
+            notified=no
+            echo "ERROR: success notification failed ! ($notify_exit_code)" >& 2
+          fi
+        fi
+        hasfailed=no
+      fi
+    else
+      ((failures++))
+      successes=0
+      if [ $failures -ge $failures_threshold ] ; then
+        [ $hasfailed != yes ] && notified=no
+        [ $notified_since -gt $monitor_failure ] && [ $monitor_failure -ge 0 ] && notified=no
+        if [ $notified = no ] ; then
+          [ -z "$verbose" ] && echo $status
+          eval $onfailure
+          notify_exit_code=$?
+          if [ $notify_exit_code -eq 0 ] ; then
+            notified=yes
+            notified_at=$(date +%s)
+          else
+            notified=no
+            echo "ERROR: failure notification failed ! ($notify_exit_code)" >& 2
+          fi
+        fi
+        hasfailed=yes
+      fi
+    fi
+    sleep $interval
+  done
+} 2>&1 | sh -c "$output"
+
